---

- name: Collect IOS facts
  hosts: cisco_routers
  gather_facts: false
  
  tasks:

    - name: Facts
      ios_facts:
        gather_subset: all

    - name: Show ansible_net_all_ipv4_addresses fact
      debug: var=ansible_net_all_ipv4_addresses
